# Generated by Django 4.1.3 on 2023-08-02 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creveApp', '0002_useraccount_creativeaccount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creativeaccount',
            old_name='phone_number',
            new_name='accountName',
        ),
        migrations.RenameField(
            model_name='creativeaccount',
            old_name='profile_pic',
            new_name='profilePic',
        ),
        migrations.AddField(
            model_name='creativeaccount',
            name='accountNumber',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='creativeaccount',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='creativeaccount',
            name='bankName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='creativeaccount',
            name='ninDocument',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='creativeaccount',
            name='phoneNumber',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='creativeaccount',
            name='validDocument',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='profile_pics/'),
        ),
    ]
