# Generated by Django 4.1.3 on 2023-08-02 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creveApp', '0006_category_delete_webmobile_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='creativeAccount',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='creveApp.creativeaccount'),
        ),
    ]
