# Generated by Django 4.1.3 on 2023-08-02 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creveApp', '0007_alter_product_creativeaccount'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='WebMobile',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='webAndMobile',
        ),
    ]
