# Generated by Django 4.1.3 on 2023-08-05 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creveApp', '0011_alter_product_creativeaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='creativeAccount',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='creveApp.creativeaccount'),
        ),
    ]
