# Generated by Django 4.1.3 on 2023-08-05 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creveApp', '0014_alter_creativeaccount_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='creativeAccount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='creveApp.creativeaccount'),
        ),
    ]
