# Generated by Django 4.1.3 on 2023-08-05 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creveApp', '0015_alter_product_creativeaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creativeaccount',
            name='account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
