# Generated by Django 4.1.3 on 2023-08-05 14:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creveApp', '0018_alter_creativeaccount_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creativeaccount',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
