# Generated by Django 4.1.3 on 2023-08-05 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creveApp', '0020_rename_creativeaccount_product_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
