# Generated by Django 4.1.3 on 2023-08-05 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creveApp', '0022_fashion_product_fashion'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='creatorProfile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='creveApp.creativeaccount'),
        ),
    ]
