# Generated by Django 4.1.3 on 2023-08-23 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creveApp', '0025_product_creatorprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='creatorProfile',
        ),
    ]
