# Generated by Django 4.1.3 on 2023-08-23 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creveApp', '0027_product_creatorprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creativeaccount',
            name='profilePic',
        ),
    ]
