# Generated by Django 4.1.3 on 2023-08-23 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creveApp', '0028_remove_creativeaccount_profilepic'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='profilePic',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='profile_pics/'),
        ),
    ]
