# Generated by Django 4.1.3 on 2023-08-26 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creveApp', '0029_account_profilepic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='productName',
            new_name='name',
        ),
    ]
