# Generated by Django 4.2.5 on 2023-11-16 12:50

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creveApp', '0032_product_image2'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WebMobile',
            new_name='Category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='cobbling',
        ),
        migrations.RemoveField(
            model_name='product',
            name='creatorProfile',
        ),
        migrations.RemoveField(
            model_name='product',
            name='fashion',
        ),
        migrations.RemoveField(
            model_name='product',
            name='funitures',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='webAndMobile',
        ),
        migrations.AddField(
            model_name='product',
            name='images',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.ImageField(upload_to='products/'), blank=True, null=True, size=None),
        ),
        migrations.DeleteModel(
            name='Cobbling',
        ),
        migrations.DeleteModel(
            name='Fashion',
        ),
        migrations.DeleteModel(
            name='Funitures',
        ),
    ]
